### ISSUE TITLE
Cannot get the bot to run on a MAC computer.....

### ISSUE THREAD

**Issue by FrodeHveding1** [GuntharDeNiro/BTCT#431] opened 2018-01-15 07:46 UTC
Over Christmas i was running the bot on a windows computer with no issues except learning how to set the strategies. Now i trying to run it on my MAC but i am having issues. When i initially run the "gunthy-gui-macos" exetuable, i get the following message:

/Users/frodehveding/Documents/Gunbot-latest-allos/Gunbot\ XT\ Edition\ -\ MacOs\ package/gunthy-gui-macos ; exit;
Frodes-MacBook-Air:~ frodehveding$ /Users/frodehveding/Documents/Gunbot-latest-allos/Gunbot\ XT\ Edition\ -\ MacOs\ package/gunthy-gui-macos ; exit;
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::5000
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server.setupListenHandle [as _listen2] (net.js:1305:14)
    at listenInCluster (net.js:1353:12)
    at Server.listen (net.js:1453:7)
    at Application.listen (/snapshot/gunbot-autoconfig/node_modules/koa/lib/application.js:64:19)
    at Object.<anonymous> (/snapshot/gunbot-autoconfig/index.js:21:5)
    at Module._compile (pkg/prelude/bootstrap.js:1226:22)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1281:12)
    at startup (bootstrap_node.js:200:16)
    at bootstrap_node.js:617:3
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
___________________________

So, when i try to run the BOT from Localhost:5000, the second terminal window does not initiate.  In addition the log is empty and there are no errors.....

Appreciate help to get my bot up and running

**Comment by anouar-zh** [comment] 2018-01-19 11:52
Check these things:

- Most likely you already have gunbot running on port 5000. 
- Otherwise an other application is running on port 5000 in the background. 
- Last option is to change the post 5000 in the config to another port. for instance 5002 en check again.

**Comment by FrodeHveding1** [comment] 2018-01-22 18:39
OK, i can get to the GUI now. Thanks. 

Next problem, In the windows at the bottom of the GUI i would expect to see the bot running, but the log is Empty...In addition, at the lowest window it says No Errors....Not sure what i am doing wrong here....

**Comment by dotpim** [comment] 2018-01-23 11:23
@FrodeHveding1 
You very probably opened gunthy-gui-macos by double clicking the file or by choosing "open with terminal" from the context menu. Both will cause Mac setting the wrong working directory for the software, causing the problem you describe.

Please start gunthy-gui-macos by first opening a terminal window, then cd to the folder your gunbot files are located, then typing ./gunthy-gui-macos
Before you do this, you might want to reboot your sytem, to make sure no old processes are still running and blocking port 5000.

Closing this issue, as it is not a bug.

**Closed by dotpim** 2018-01-23 11:23 UTC
