### ISSUE TITLE
Sell cycle callback: "balance is lower than minimum value to buy", version 4.0.4

### ISSUE THREAD

**Issue by gsp-beta-admin** [GuntharDeNiro/BTCT#43] opened 2017-08-18 16:21 UTC
<img width="1022" alt="screen shot 2017-08-18 at 9 12 27 am" src="https://user-images.githubusercontent.com/18335589/29467531-bdf852d0-83f5-11e7-9e32-e304462e4ad6.png">

What's going on here? Why would gunbot give me the response: "balance is lower than minimum value to **BUY**, during a sell cycle?

Strategy:

	"bb": {
		"BTC_TRADING_LIMIT": 0.01,
		"PERIOD": 15,
		"GAIN": 0.3,
		"HIGH_BB": 25,
		"LOW_BB": 25,
		"PANIC_SELL": false,
		"DOUBLE_UP": true,
		"STOP_LIMIT": 60,
		"BUY_ENABLED": true,
		"MIN_VOLUME_TO_BUY": 0.0005,
		"MIN_VOLUME_TO_SELL": 0.0005
	}

**Comment by GuntharDeNiro** [comment] 2017-08-23 22:50
Not a bug

**Comment by GuntharDeNiro** [comment] 2017-08-23 22:58
This has been fixed in v4.0.5, it was a wrong "message" displayed by the bot

**Closed** 2017-08-23 22:59 UTC
