### ISSUE TITLE
v5.0.2 : With pure BB the bot does not sell ?

### ISSUE THREAD

**Issue by ntsili** [GuntharDeNiro/BTCT#99] opened 2017-09-13 22:27 UTC
![untitled3](https://user-images.githubusercontent.com/27147058/30403286-391bfba6-98e1-11e7-8e5e-493974f20d45.png)

It's on Poloniex. On the left you see BTC-NXT and on the right BTC-XRP. On the bottom you see the log. 
The bot seems to understand correctly the limits that are set: green line is for buy and red line is for sell. 
So it bought correctly when it touched the green line for both coins. 
Later, the price stayed higher than red line for about 30 minutes and it didn't sell!! (+0,8 and +0,1). I lost both trades. 
Is there a bug that prevents the bot sell when on pure BB? It's the first time I encounter such behavior from the bot. 

			"PERIOD": 15,
			"GAIN": 0,
			"HIGH_BB": 60,
			"LOW_BB": 15,
			"STDV": 2,
			"SMAPERIOD": 80,

**Comment by GuntharDeNiro** [comment] 2017-09-14 09:14
i cant reproduce this, please someone else confirms/denies, thanks

**Comment by ntsili** [comment] 2017-09-14 10:05
![img_3868](https://user-images.githubusercontent.com/27147058/30423894-9357a724-9944-11e7-8ca0-7c9f36277863.PNG)

Here is today's trade history... only buys... very strange as I didn't have this issue with premiums v5 versions...

**Comment by ntsili** [comment] 2017-09-14 12:14
![img_3870](https://user-images.githubusercontent.com/27147058/30429129-a36db380-9956-11e7-9c10-71174c581107.PNG)

16 trades, without selling, and counting... 
As I wrote in the first post, the price goes clearly above the red line, but the bot does not sell... I can't figure out why...

**Comment by ntsili** [comment] 2017-09-14 22:01
![untitled](https://user-images.githubusercontent.com/27147058/30457672-94809458-99a8-11e7-84b6-fb67a04e58b6.png)
GuntharDeNiro, clearly it says that it can sell, but it doesn't do it. It repeats that a lot of times... 
The BTC balance is ok. I am on v5.0.4 actually. 
Any idea about this behavior? 

ThanX
Nick

**Comment by ntsili** [comment] 2017-09-14 22:23
**SOLVED**

In fact the "WATCH_MODE" was turned on. 

I propose to change the issue to the following: 
**BUG**: "If WATCH_MODE is turned on the bot bypasses it and makes sells but it cannot sell"

**Comment by marciosato** [comment] 2017-09-14 22:29
sometimes i had the same behavior, and "WATCH_MODE" was false =/

![2017-09-14-19 26 42-web](https://user-images.githubusercontent.com/16124851/30458679-035a03f8-9983-11e7-8de4-06c487bc9d53.jpg)

**Comment by 3kynox** [comment] 2017-09-15 13:54
We are now sticked to 504, closing here.

**Closed by 3kynox** 2017-09-15 13:54 UTC
Labels: invalid
