### ISSUE TITLE
v504 Bot rebuys higher than just sold

### ISSUE THREAD

**Issue by utdrmac** [GuntharDeNiro/BTCT#114] opened 2017-09-15 20:30 UTC
I don't have the logs unfortunately. All I have is Polo history. Using pure stepgain.

<img width="726" alt="nxt rebuy high" src="https://user-images.githubusercontent.com/4413670/30502009-280dafd6-9a2a-11e7-8cd5-a13aa78a7b24.png">

```
2017-09-15 18:24:01 | Buy | 0.00001870 | 77.51462416 | 0.00144952
2017-09-15 18:20:26 | Sell | 0.00001866 | 548.67986799 | 0.01023836
2017-09-15 17:45:44 | Buy | 0.00001818 | 550.05500550 | 0.00999999
```

```
"stepgain": {
  "BTC_TRADING_LIMIT": 0.01,
  "PERIOD": 5,
  "BUYLVL1": 1.5,
  "BUYLVL2": 1.6,
  "BUYLVL3": 70,
  "SELLLVL1": 1.5,
  "SELLLVL2": 1.6,
  "SELLLVL3": 70,
  "BUYLVL": 2,
  "SELLLVL": 2,
  "LASTPOINTS": 4,
  "AVGPOINTS": 20,
  "AVGMINIMUM": 0.00000001,
  "EMA1": 4,
  "EMA2": 2,
  "PANIC_SELL": false,
  "STOP_LIMIT": 60,
  "BUY_ENABLED": true,
  "MIN_VOLUME_TO_BUY": 0.001,
  "MIN_VOLUME_TO_SELL": 0.001
}
```

**Comment by GuntharDeNiro** [comment] 2017-09-16 23:43
duplicate of #105

**Closed by GuntharDeNiro** 2017-09-16 23:43 UTC
Labels: duplicate
