### ISSUE TITLE
[Idea] Improvements for doubledown

### ISSUE THREAD

**Issue by strongboy54** [GuntharDeNiro/BTCT#94] opened 2017-09-13 06:16 UTC
Hello,
Rather than having the double down feature keep buying to just lower the sell price, it should wait for a new buy signal using the strategy it is on. It will be easy to implement, can be used for all strategies and will vastly improve doubledown. Most importantly, it'll make double down actually useful.

Take Stepgain for example(Because that's what I use), Buy signal at 0.06 BTC, it buys, price goes down to 0.05 BTC, either you can buy manually or hold it for god knows how long.
Instead, GB should wait for another buy signal and buy then. If it wasn't holding anything it would've bought at that time anyway.

This should be easy to implement, it'll require to simply have the strategy "start again" but retaining the original buy price.

If anyone else believes this is a great idea, please do explain it as I can see I'm not the best at trying to explain this haha.
General idea would be at least to buy on signals continuously, ignoring if you've bought previously, and sell at overrall x% profit.

Please also implement double down for stepgain too!

**Comment by GuntharDeNiro** [comment] 2017-09-14 09:16
I'll backtest this

**Comment by GuntharDeNiro** [comment] 2017-09-18 22:20
duplicate of #58

**Closed by GuntharDeNiro** 2017-09-18 22:20 UTC
Labels: duplicate, enhancement
