### ISSUE TITLE
10.7.2 build 836 Reversal Trading NOT WORKING?

### ISSUE THREAD

**Issue by TyPaul2** [GuntharDeNiro/BTCT#635] opened 2018-10-02 16:39 UTC
Using stepgain strategy and trying to use RT to no avail! The RT_GAIN is supposed to be a placeholder according to the Wiki, however it is the only setting that controls the RT SELL (RT_SELLLVL's" appear to have no effect). Also, the BUYBACK figure in the logs equals Breakeven point in logs (I have experimented with all the other RT & relative TM settings and nothing seems to change the BUYBACK).  Doesn't it make sense that if an RT SELL happens and the trend reverses that the BUYBACK should happen near the RT SELL and not the much higher Breakeven point? As it appears now, RT is causing the same loss to incur twice when the trend reverses. I am not finding the Wiki to be helpful. Is this a bug or can anyone please let me know what I can read/watch/reference to learn how to use RT to do as it suggests it should do?????

**Comment by Sir80** [comment] 2018-10-03 18:15
Same here... gunbot bought IOTX @218 reversed till @201 and last action sold @197... 
Sadly @197 was the bottom and IOTX raised meanwhile till @208. gunbot says Breakeven is @214.
It does feel wrong to see the coin raise back to breakeven when gunbot successfully reversed so far down...
I mean a raise of 5% and no buyback?

It seems this feature is like a coinflip. Gunbot did a rt_buy and coin starts raising again? = profit. Gunbot is in rt_sell mode and coin raise again? Well...unlucky mate...wait and lose possible profit till breakeven... :/

**Comment by shaman79** [comment] 2018-12-01 14:04
Exactly the same here. Nasty bug that is actually able to suck you out of money. I personally lost several hundreds EUR due to this. Seems that the problem is the break even calculation. FIX IT, PLEASE!

**Comment by grumpy-kitty** [comment] 2019-05-11 17:41
Should be fixed.

**Closed** 2019-05-11 17:41 UTC
