### ISSUE TITLE
Being told I don't have enough gunthy, asking for 2500 

### ISSUE THREAD

**Issue by CryptoCory** [GuntharDeNiro/BTCT#710] opened 2019-05-10 18:57 UTC
I have the standard license with only one exchange set up. Worked fine, no changes made but now get this msg on start up:

UI Server Deployed: http://localhost:5000
Total Required Balance *Now*: 2500
Total Required Balance *Soon*: 2500
Total Available Balance: 1000
Your Balance is: 1000. You need 2500 account balance of GUNTHY tokens.
Removing binance from running.
Loading data....

It hangs from here. I checked to ensure only that one exchange is set up. How do I fix this?

C

**Comment by salty2011** [comment] 2019-05-11 09:01
I am also getting this issue with gunbot on version 12.8.9 and 12.9.2,

**Comment by whitegoblin420** [comment] 2019-05-11 12:14
I'm having this problem as well. Per my thread on their forums here: [https://gunthy.org/forum/index.php/topic,3806.msg15231.html#msg15231](https://gunthy.org/forum/index.php/topic,3806.msg15231.html#msg15231) The Administrator "GrumpyKitty" replied: "No, that's caused by a bug. Update to v12.9.9."  :(

**Comment by whitegoblin420** [comment] 2019-05-11 13:00
Just got a response from GumpyKitty: _"You should be on Telegram, i.e. join the Gunthy Elite group to receive the fastest updates. I've pinged Gunthar to add the build to GitHub, but I have no ETA on this. Usually major versions are release at the same time across all platforms."_

**Comment by grumpy-kitty** [comment] 2019-05-11 17:30
I've pushed the binaries to GitHub: https://github.com/GuntharDeNiro/BTCT/releases/tag/1299. The latest build solves this issue and I'll therefore close it.

**Closed by grumpy-kitty** 2019-05-11 17:30 UTC
