### ISSUE TITLE
Massive Ram Usage Mac

### ISSUE THREAD

**Issue by yoshilee** [GuntharDeNiro/BTCT#204] opened 2017-11-12 20:29 UTC
Over time Gunboat v6.0.1 eating up all ram. Having that issue on two mac systems, running 2 or 30 pairs make no difference. Over a couple of hours all ram gets filled (16GB in my case).

**Comment by smportis** [comment] 2017-11-12 22:04
Agree - 24gb and it took the machine to a crawl overnight. Had to reboot. Memory leak somewhere.

**Comment by Utone** [comment] 2017-11-12 22:23
There is a known memory leak in Firefox (read about it online not sure if it's fixed by now but think it's is more stable than chrome.  Also Chrome with some Bittrex tabs and polo + tradingview made my macbook pro retina 16GB ram freeze and crash to Chinese error message, had to quickly close the offending tabs for it not to repeat...NOT that this is it, but experiment... 

I even made a manual buy way over market price on Bittrex because the browser simply didn't update...so beware...

In my case other browsers like Safari and Chromium do not fare better either and after an hour or so the fans are running at max and everything gets sluggish as hell.
Have several Issues with Sjakils GUI not sure what is the culprit.

**Comment by equalgeek** [comment] 2017-11-12 22:23
If you just close the browser without killing the bot it works just fine and dumps all the memory. It has something to do with the log tab. I have just been closing the browser and then leaving it that way until I need to change something.

**Comment by useR210961** [comment] 2017-11-12 22:33
Is this memory leak happening on the host or on the client machine (in case of a VPS)? I got ocnfused with those browser arguments?! For now I did not upgrade and am still running 4.x since 5.x has too much problems as well.

**Comment by equalgeek** [comment] 2017-11-12 22:36
@equalgeek Or you can just close that tab, wait a little bit and then reopen it and it's far more responsive. At least this is a good temp fix for the time being.

**Comment by equalgeek** [comment] 2017-11-12 22:52
@useR210961 XT has a browser gui and this is what they are talking about.. doesn't matter if it's on a vps or client machine.

**Comment by useR210961** [comment] 2017-11-12 23:08
@equalgeek thank you for that fast response! I know about the GUI, but I wonder if the node server on the VPS will casue a memory leak, or if it is just some crappy frontend and with this the client browser causing the leak. So if I use the gui version, the bot will still run without memory leaks and I just should not let my client browser be connected for too long?

**Comment by GuilhermeMedeiros** [comment] 2017-11-12 23:14
It's just browser related guys. Just reload the page and it should be fine.
I'm gonna investigate what's going on and try to fix it for the next release.

**Comment by equalgeek** [comment] 2017-11-12 23:24
@useR210961 The bot itself does not have a memory leak. It is only the web gui that has the issue as @GuilhermeMedeiros stated. If you just close the tab or browser once gunthy is running then there is no issue. It is only when the web gui is open, not the bot. Hopefully that is clear enough :]

**Comment by useR210961** [comment] 2017-11-12 23:37
@equalgeek 
@GuilhermeMedeiros 
great, thanks for the info.

**Comment by smportis** [comment] 2017-11-13 01:43
Thanks guys!! Good to know. I tried closing the browser but did not wait long enough for the memory to get flushed I guess. Will try that next time and see how quickly the memory gets released. 

Great GUI !!!!! Can't wait for new features!

**Comment by yoshilee** [comment] 2017-11-13 06:02
Great News! Leaving the browser closed, everything is fine for now. Thanks

**Comment by smportis** [comment] 2017-11-13 14:05
My experience is different and may lead to more insight. 

This morning, with the browser open, memory had crept up to 21GB from 12 overnight. Killed the browser window, and after 10 min, did not see a drop in memory usage. Killed the gunthy-gui-macos process and saw an immediate drop in memory. 

Restarted the process, and then the GUI in browser, and memory remained at 12GB. 

I will try to confirm that leaving the browser closed leads to no memory usage as @yoshilee stated above. 

![screen shot 2017-11-13 at 7 59 22 am](https://user-images.githubusercontent.com/7082654/32729405-42c910d4-c849-11e7-86f3-194701a3e75c.png)

**Comment by GuntharDeNiro** [comment] 2017-11-13 20:58
not a bug as @GuilhermeMedeiros pointed out

**Closed by GuntharDeNiro** 2017-11-13 20:58 UTC
