### ISSUE TITLE
Bot buys and sells at same price within 1-2 secs

### ISSUE THREAD

**Issue by smportis** [GuntharDeNiro/BTCT#116] opened 2017-09-16 06:56 UTC
Stepgain  504. Bot buys and sells at the same time, in that order. Several users reporting this. 

"stepgain": {
            "BTC_TRADING_LIMIT": 0.01,
            "PERIOD": 15,
            "BUYLVL1": 0.9,
            "BUYLVL2": 1.2,
            "BUYLVL3": 9,
            "SELLLVL1": 1,
            "SELLLVL2": 1.6,
            "SELLLVL3": 4.2,
            "BUYLVL": 2,
            "SELLLVL": 2,
            "LASTPOINTS": 5,
            "AVGPOINTS": 15,
            "AVGMINIMUM": 0.00000001,
            "EMA1": 3,
            "EMA2": 6,
            "PANIC_SELL": false,
            "DOUBLE_UP": false,
            "STOP_LIMIT": 4.5,
            "BUY_ENABLED": true,
            "MIN_VOLUME_TO_BUY": 0.001,
            "MIN_VOLUME_TO_SELL": 0.001
        },

![screen shot 2017-09-16 at 1 53 38 am](https://user-images.githubusercontent.com/7082654/30510019-3f1133f8-9a82-11e7-866f-911e8afafd09.png)

![screen shot 2017-09-16 at 1 52 57 am](https://user-images.githubusercontent.com/7082654/30510018-3f0f6276-9a82-11e7-8434-c8ff76ed810d.png)

**Comment by thejeremywhite** [comment] 2017-09-16 06:59
Try switching EMA 1 and 2 to this:
 "EMA1": 3, 
 "EMA2": 6,

**Comment by smportis** [comment] 2017-09-16 12:30
jeremy, those are my values. Did you mean something else.

**Comment by tandyuk** [comment] 2017-09-16 12:31
No, yo uhave:
"EMA1": 3,
"EMA2": 6,
Swap them round

**Comment by smportis** [comment] 2017-09-16 13:16
I get it, swap them. 

What's the thought behind swapping? 

--
Scott M Portis
Owner, Moe's Southwest Grill | www.Moes.com
10 Locations in Middle TN
615-300-3696 (c)

**Comment by thejeremywhite** [comment] 2017-09-16 17:30
EMA1 is the "long" Moving Average
EMA2 is the "short" Moving Average
When the short moving average is above long moving average it is considered an uptrend. And when it is going downward and Crosses to the long average it is a downtrend. That's the short explanation. If you have those two mixed up you would be giving GunBot incorrect signals to buy and sell

**Comment by GuntharDeNiro** [comment] 2017-09-16 23:44
duplicate of #105

**Closed by GuntharDeNiro** 2017-09-16 23:44 UTC
