### ISSUE TITLE
Bug: Bot still buying at top of BB on Bittrex with default BB settings.

### ISSUE THREAD

**Issue by softgripper** [GuntharDeNiro/BTCT#118] opened 2017-09-16 15:48 UTC
Still same behavior as this closed issue Gunthar https://github.com/GuntharDeNiro/BTCT/issues/62.  Is this just Bittrex?

There is no output log from the bot, so I can't get the exact numbers.  I assume the calculations are correct, but I think perhaps the data collection has a bug - eg, too many requests effectively making the EMA period tick very quickly, or the EMAs are reversed, and EMAshort should be below EMAlong when a buy happens?

If this is not a bug, please let me know how I can actually get this thing trading at 40% above the lower BB.  I'd be very successful if this was trading at 40% and 40% according to the Bittrex BB, but it is trading on some invisible Gunbot BB which is very very different from Bittrex, and not buying in the right places at all.

I am reverting back to 3.3.2 for the time being.

![broken-trade](https://user-images.githubusercontent.com/26377893/30513597-68f46ce0-9b49-11e7-8677-a48b5f74fd3a.jpg)

> 09/17/2017 01:10:28 AM | 09/17/2017 01:10:28 AM | BTC-KMD | Limit Buy | 0.00049320 | 30.41362530 | 30.41362530 | 0.00049300 | -0.01503170
> -- | -- | -- | -- | -- | -- | -- | -- | --
> 09/17/2017 12:59:56 AM | 09/17/2017 12:59:56 AM | BTC-KMD | Limit Sell | 0.00047715 | 32.11991434 | 32.11991434 | 0.00047714 | 0.01528770

>     "bb": {
>       "BTC_TRADING_LIMIT": 0.015,
>       "PERIOD": 15,
>       "EMA1": 2,
>       "EMA2": 4,
>       "GAIN": 2,
>       "HIGH_BB": 40,
>       "LOW_BB": 40,
>       "STDV": 2,
>       "SMAPERIOD": 50,
>       "PANIC_SELL": false,
>       "DOUBLE_UP": false,
>       "STOP_LIMIT": 60,
>       "BUY_ENABLED": true,
>       "MIN_VOLUME_TO_BUY": 0.001,
>       "MIN_VOLUME_TO_SELL": 0.001
>     },

**Comment by lucidqdreams** [comment] 2017-09-16 19:02
![example1](https://user-images.githubusercontent.com/6086602/30515077-58f5f584-9ad6-11e7-8aab-976c4ac8a3ca.PNG)
![example2](https://user-images.githubusercontent.com/6086602/30515078-590ae656-9ad6-11e7-8dbd-06088f4bff3f.PNG)

Bot seemed to buy and sell at a good price made the margin, then brought right back in while the price seems very high.  

		"bb": {
			"BTC_TRADING_LIMIT": 0.001,
			"PERIOD": 15,
			"EMA1": 2,
			"EMA2": 4,
			"GAIN": 2,
			"HIGH_BB": 40,
			"LOW_BB": 25,
			"STDV": 2,
			"SMAPERIOD": 50,
			"PANIC_SELL": false,
			"DOUBLE_UP": true,
			"STOP_LIMIT": 30,
			"BUY_ENABLED": true,
			"MIN_VOLUME_TO_BUY": 0.0001,
			"MIN_VOLUME_TO_SELL": 0.0001
		},

**Comment by softgripper** [comment] 2017-09-16 22:20
I'll start up a BB bot today with buy enabled and check the BB upper/lower against what Bittrex is showing.

**Comment by GuntharDeNiro** [comment] 2017-09-17 00:10
uhm i'm not closing this as a not bug because you provided a lot of informations that i need lol.
I'll be back with something more detailed.

**Comment by softgripper** [comment] 2017-09-17 00:19
Great!  I keep looking at the Bittrex BB and imagine the bot trading at 40/40 and get very surprised when things like this happen.

**Comment by realWiZ** [comment] 2017-09-17 13:42
You have to check BB output from the bot. What i found is that BB are working fine in a stable market (tested 25 pairs with different volumes) while in other market conditions (coins pumping or dumping) BB are not ok and so far I am not able to fine tune them no matter which parameters I change. Two examples from today morning:

NXS (stable market):

![cattura2](https://user-images.githubusercontent.com/32036096/30521328-36562984-9bbe-11e7-9cfd-166091eea9f8.PNG)
![cattura2-bittrex](https://user-images.githubusercontent.com/32036096/30521330-3e531ae8-9bbe-11e7-9e34-4031bbda838b.PNG)

as it is possible to see, BB from the bot are almost matching the exchange ones.

BAT

![cattura](https://user-images.githubusercontent.com/32036096/30521338-58248952-9bbe-11e7-9e62-f35ae68afcba.PNG)
![cattura-bittrex](https://user-images.githubusercontent.com/32036096/30521347-669cab68-9bbe-11e7-910f-1d1211fc2844.png)

in this case we are right after a pump, and as you can see the BB are too tight and so the odd buys are explained. I have tried to modify many parameters (separately and simultaneously) but when the market is pumping/dumping it seems that there is no way to match the BB values. Same behaviour yesterday with EDG-BTC.

Please post your BOT output if you are experiencing issues with BB so we can point gun in the correct direction.

**Comment by Gnorbe** [comment] 2017-09-17 15:22
I confirm that the BB calculated by Gunbot are very often different from the Bittrex or Poloniex charts. **The problem is that the BB are very difficult to configure and, in most case, is impossible**. I've tried to modify any BB-related parameters into config file, but remain far from the Bittrex chart.

One example:

BTC-NEO on Bittrex (15 min candlestick)

![neo-bittrex](https://user-images.githubusercontent.com/31937016/30522195-6f682976-9bcc-11e7-9ca1-317d0393bc40.JPG)


Gunbot with BB strategy and predefined parameters:

![neo_gunbot](https://user-images.githubusercontent.com/31937016/30522146-c3318e36-9bcb-11e7-9a93-010a93634bb9.jpg)

**Comment by realWiZ** [comment] 2017-09-17 15:24
Checking further pairs (yesterday i focused mostly on low volume pairs) I seen that the issue seems the volume itself. Particularly, for high volume coins BB seem not correct. A few examples:

ETH
![eth](https://user-images.githubusercontent.com/32036096/30522170-12b8f55c-9bcc-11e7-9854-ceb1013ad3b8.PNG)
![eth-bittrex](https://user-images.githubusercontent.com/32036096/30522171-143ac0e0-9bcc-11e7-9dae-38986d03dffa.png)

OK
![ok](https://user-images.githubusercontent.com/32036096/30522173-19beb1f2-9bcc-11e7-94f4-60b58c768eb8.PNG)
![ok-bittrex](https://user-images.githubusercontent.com/32036096/30522174-1b499eec-9bcc-11e7-8ad7-06575ac4a899.PNG)

NEO
![neo](https://user-images.githubusercontent.com/32036096/30522176-210863a4-9bcc-11e7-9827-89271fbdd0e8.PNG)
![neo-bittrex](https://user-images.githubusercontent.com/32036096/30522178-2280d0a4-9bcc-11e7-9d03-3140edf0c65b.PNG)

I am using the following parameters that should affect BB calculation:

1) period storage ticker-->5000
2) interval ticker update -->40000 (40 seconds)
3) smaperiod-->150
4)stdv 2

**Comment by softgripper** [comment] 2017-09-17 15:53
I wrote some code today that exactly mirrors the BB generated from the BitTrex chart.  I'll supply it to Gunthar if he wants.

**Comment by GuntharDeNiro** [comment] 2017-09-18 22:17
fixed in v5.0.5
Thanks for reporting this!

**Closed by GuntharDeNiro** 2017-09-18 22:17 UTC

**Comment by utdrmac** [comment] 2017-10-16 15:27
@softgripper Could you share that code publicly?

**Comment by softgripper** [comment] 2017-10-16 16:24
@GuntharDeNiro has it.  Unfortunately, I have the same problems from this issue in 5.0.5.  with and without Gunthy API for 15min bittrex.
